steps:
      - name: 'gcr.io/cloud-builders/npm'
        args: ['ci']
      # Build
      - name: 'gcr.io/cloud-builders/npm'
        args: ['run', 'build']
      # Deploy
      - name: gcr.io/project-id/firebase
        args: ['deploy', '--project=project-id', '--only=hosting']